version: '3'

services:
  app:
    build: .
    container_name: velis-website
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
    restart: always
    networks:
      - velis_network

networks:
  velis_network:
    driver: bridge
